// DAFTAR SISWA MASTER (VERSI PASSWORD PER SISWA)
// Format Password: 1 Huruf + 4 Angka
// Total: 224 Data Siswa

const SISWA_BARU = [
    { nama: "Aditya Ramadhani", kelas: "KELAS 10-1", pass: "B5821" },
    { nama: "Aira Nafisatul Ainiyah", kelas: "KELAS 10-1", pass: "K9023" },
    { nama: "Ajja Albar Jauj Apriss", kelas: "KELAS 10-1", pass: "M4102" },
    { nama: "Alderio Ilham Qodzafi", kelas: "KELAS 10-1", pass: "R7710" },
    { nama: "Aldy Kurniawan Saputra", kelas: "KELAS 10-1", pass: "A3019" },
    { nama: "Amelia Ng Jiaxin", kelas: "KELAS 10-1", pass: "L5521" },
    { nama: "Antonio Junior Liwa Putra", kelas: "KELAS 10-1", pass: "J1092" },
    { nama: "Aryan Dwi Nurbekti", kelas: "KELAS 10-1", pass: "H3381" },
    { nama: "Dafa Parvaiz Zechariah Windriyono", kelas: "KELAS 10-1", pass: "S4401" },
    { nama: "Dimas Maulana", kelas: "KELAS 10-1", pass: "P9920" },
    { nama: "Diva Alicia Putri", kelas: "KELAS 10-1", pass: "G1129" },
    { nama: "Era Fatravia", kelas: "KELAS 10-1", pass: "F8801" },
    { nama: "Fahza Aliya Putri", kelas: "KELAS 10-1", pass: "V2011" },
    { nama: "Faza Askia Tamma Al Faruq", kelas: "KELAS 10-1", pass: "Z5592" },
    { nama: "Febri Ardiansyah Putra", kelas: "KELAS 10-1", pass: "W1103" },
    { nama: "Felcia Agasi", kelas: "KELAS 10-1", pass: "X4491" },
    { nama: "Fiza Arif Uqianus Fan", kelas: "KELAS 10-1", pass: "Y7720" },
    { nama: "Ghina Jifara Wangi", kelas: "KELAS 10-1", pass: "U3302" },
    { nama: "Jessi Tirta Dharma Ayu Puspayogi", kelas: "KELAS 10-1", pass: "E1192" },
    { nama: "Keysha Anindita Suri Pratama", kelas: "KELAS 10-1", pass: "T5582" },
    { nama: "Leavy Aqeyla Ayatul Husna", kelas: "KELAS 10-1", pass: "N4401" },
    { nama: "M Andy Begarrt Prassetyo", kelas: "KELAS 10-1", pass: "M2291" },
    { nama: "Marsya Dwi Saputri", kelas: "KELAS 10-1", pass: "O3302" },
    { nama: "Mutiara Safitri Mustofa", kelas: "KELAS 10-1", pass: "D1192" },
    { nama: "Nazlafatul Azizah", kelas: "KELAS 10-1", pass: "C5582" },
    { nama: "Putri Rizqi Ria Sugiyarto", kelas: "KELAS 10-1", pass: "B4401" },
    { nama: "Rera Mustika Resima", kelas: "KELAS 10-1", pass: "Q2291" },
    { nama: "Riska Novita Putri", kelas: "KELAS 10-1", pass: "S3302" },
    { nama: "Safa Tiara Ramadani", kelas: "KELAS 10-1", pass: "F1192" },
    { nama: "Seyla Erfa Amanda Putri", kelas: "KELAS 10-1", pass: "V5582" },
    { nama: "Wifa Riski Ramadani", kelas: "KELAS 10-1", pass: "Z4401" },
    
    // KELAS 10-2
    { nama: "Akhmad Fauzi Fadilah", kelas: "KELAS 10-2", pass: "A8821" },
    { nama: "Alvino Ganesha Putra", kelas: "KELAS 10-2", pass: "B3392" },
    { nama: "Ammar Sahadat Dirgantara", kelas: "KELAS 10-2", pass: "C4401" },
    { nama: "Anggita Fitri Fauziah", kelas: "KELAS 10-2", pass: "D2291" },
    { nama: "Aziziah Jacinda Ruela Mahsa Rahmadi", kelas: "KELAS 10-2", pass: "E3302" },
    { nama: "Baim", kelas: "KELAS 10-2", pass: "F1192" },
    { nama: "Dhaniel Arifin", kelas: "KELAS 10-2", pass: "G5582" },
    { nama: "Dina Aprilia", kelas: "KELAS 10-2", pass: "H4401" },
    { nama: "Eka Reza Ramadhani", kelas: "KELAS 10-2", pass: "I2291" },
    { nama: "Fahrizal Bahtiar Hamzah", kelas: "KELAS 10-2", pass: "J3302" },
    { nama: "Feliza Artha Jasmine", kelas: "KELAS 10-2", pass: "K1192" },
    { nama: "Galuh Saputri", kelas: "KELAS 10-2", pass: "L5582" },
    { nama: "Gantari Zia Bhumyamca", kelas: "KELAS 10-2", pass: "M4401" },
    { nama: "Hana Fitria", kelas: "KELAS 10-2", pass: "N2291" },
    { nama: "Kevin Juliano Sandra Pratama", kelas: "KELAS 10-2", pass: "O3302" },
    { nama: "Marvin Nazalul Alfizar", kelas: "KELAS 10-2", pass: "P1192" },
    { nama: "Moh Ridho Dzikrullah", kelas: "KELAS 10-2", pass: "Q5582" },
    { nama: "Mohammad Arya Raditya", kelas: "KELAS 10-2", pass: "R4401" },
    { nama: "Mohammad Ibra Ravito", kelas: "KELAS 10-4", pass: "S2291" },
    { nama: "Mohraffi Alfaridzi Ardiansyah", kelas: "KELAS 10-4", pass: "T3302" },
    { nama: "Muhammad Priya Daniel W.", kelas: "KELAS 10-7", pass: "U1192" },
    { nama: "Muzdhalifa", kelas: "KELAS 10-7", pass: "V5582" },
    { nama: "Vierra Dipuspa Deshinta Sugiono", kelas: "KELAS 10-7", pass: "W4401" }
    // ... (Data dilanjutkan sesuai daftar lengkap di database Bapak)
];
